---
apiVersion: batch/v1
kind: Job
metadata:
  name: phenovar-client
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 10800 #3 hours,
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - image: ferlabcrsj/phenovar:c928a2c6be176e1f64bbe9aafe54e0a3adf8acfc-1768504822
          name: token-generation
          command: ["python", "/opt/entrypoint/entrypoint.py", "get_user_token"]
          env:
            - name: PHENOVAR_CREATE_MISSING_USER
              value: "true"
            - name: PHENOVAR_CLEAN_EXISTING_USER_TOKEN
              value: "false"
            - name: PHENOVAR_TOKEN_FILE
              value: /opt/phenovar-token/token
            - name: PHENOVAR_USERNAME
              value: "automaton"
            - name: MYSQL_HOST
              value: phenovar-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USE_SSL
              value: "false"
            - name: CONN_MAX_AGE
              value: "0"
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "128Mi"