apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  secretName: __UNDEFINED__
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Ferlab Sainte-Justine
  isCA: false
  privateKey:
    algorithm: __UNDEFINED__
    encoding: __UNDEFINED__
    size: 4096
  usages:
    - server auth
    - client auth
  dnsNames:
    - __UNDEFINED__
  issuerRef:
    name: __UNDEFINED__
    kind: ClusterIssuer