apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: __UNDEFINED__
    server: __UNDEFINED__
    privateKeySecretRef:
      name: __UNDEFINED__
    solvers:
    - http01:
        ingress:
          class: nginx