---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arranger
  template:
    metadata:
      labels:
        app: arranger
    spec:
      containers:
        - image: overture/arranger-server:98162e0
          name: arranger
          resources:
            requests:
              memory: "256Mi"
              cpu: '0.5'
            limits:
              memory: "512Mi"
              cpu: '1'
          envFrom:
          envFrom:
            - configMapRef:
                name: arranger-es-configs
            - configMapRef:
                name: arranger-keycloak-configs
            - secretRef:
                name: arranger-keycloak-credentials