apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: manage-airflow-users
  namespace: airflow
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: airflow
          volumes:
            - name: pod-template-file
              configMap:
                name: airflow-config-kubernetes-template
                defaultMode: 0444
            - name: scripts
              configMap:
                name: airflow-scripts
                defaultMode: 0555
            - name: secrets
              secret:
                secretName: airflow-secrets
          restartPolicy: OnFailure
          containers:
            - name: manage-airflow-users
              image: apache/airflow:1.10.14-python3.7
              env:
                - name: AIRFLOW__CORE__EXECUTOR
                  value: KubernetesExecutor
                - name: AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE
                  value: /opt/airflow/k8/airflow_template.yml
                - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
                  valueFrom:
                    secretKeyRef:
                      name: airflow-db-connection
                      key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              envFrom:
                - configMapRef:
                    name: airflow-config-core
                - configMapRef:
                    name: airflow-config-secrets
                - configMapRef:
                    name: airflow-config-cli
                - configMapRef:
                    name: airflow-config-api
                - configMapRef:
                    name: airflow-config-operators
                - configMapRef:
                    name: airflow-config-webserver
                - configMapRef:
                    name: airflow-config-email
                - configMapRef:
                    name: airflow-config-scheduler
                - configMapRef:
                    name: airflow-config-kubernetes
                - secretRef:
                    name: airflow-smtp
                - secretRef:
                    name: airflow-fernet-key
                - secretRef:
                    name: airflow-webserver-flask-key
              volumeMounts:
                - name: pod-template-file
                  mountPath: /opt/airflow/k8
                  readOnly: true
                - name: scripts
                  mountPath: /opt/airflow/scripts
                  readOnly: true
                - name: secrets
                  mountPath: /opt/airflow/secrets
                  readOnly: true
              command:
                - python
              args:
                - /opt/airflow/scripts/manage-users.py