resources:
  - all.yaml
patches:
  - path: kustom-ca-cert.yaml
    target:
      kind: Deployment
      name: airflow-webserver
  - path: kustom-ca-cert.yaml
    target:
      kind: Deployment
      name: airflow-triggerer
  - path: kustom-ca-cert.yaml
    target:
      kind: Deployment
      name: airflow-scheduler
