---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  namespace: spark
  labels:
    name: spark
data:
  spark-defaults.conf: |
    spark.master=k8s://https://kubernetes.default.svc.cluster.local
    spark.submit.deployMode=cluster
    spark.kubernetes.namespace=spark
    spark.kubernetes.authenticate.driver.serviceAccountName=spark
    spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.fast.upload=true
    spark.hadoop.fs.s3a.connection.ssl.enabled=false
    spark.hadoop.fs.s3a.path.style.access=true
    spark.hadoop.hive.metastore.uris=thrift://hive-metastore.default.svc.cluster.local:9083
    spark.sql.warehouse.dir=s3a://spark/wharehouse