---
apiVersion: batch/v1
kind: Job
metadata:
  name: phenovar-create-databases
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: ferlabcrsj/phenovar:8fbc9b826ad50f3891849499b3e5bda59b7c6c6a-1769101634
          name: phenovar-create-databases
          command: ["python", "/opt/entrypoint/entrypoint.py", "create_databases"]
          env:
            - name: MYSQL_HOST
              value: phenovar-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USE_SSL
              value: "false"
            - name: PHENOVAR_ALLOW_DB_CREATION_OVERWRITE
              value: "false"
            - name: DJANGO_CONN_MAX_AGE
              value: "0"
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"