---
apiVersion: batch/v1
kind: Job
metadata:
  name: phenovar-create-databases
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: ferlabcrsj/phenovar:c928a2c6be176e1f64bbe9aafe54e0a3adf8acfc-1768504822
          name: phenovar-create-databases
          command: ["python", "/opt/entrypoint/entrypoint.py", "create_databases"]
          env:
            - name: MYSQL_HOST
              value: phenovar-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USE_SSL
              value: "false"
            - name: PHENOVAR_ALLOW_DB_CREATION_OVERWRITE
              value: "false"
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"