---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: id-service
  name: id-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: id-service
  template:
    metadata:
      labels:
        app: id-service
    spec:
      containers:
        - image: ferlabcrsj/id-service:__UNDEFINED__
          name: id-service
          env:
            - name: PGHOST
              value: id-service-db
            - name: PGDATABASE
              value: id-service
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: id-service-db-credentials
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: id-service-db-credentials
                  key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: '0.25'
            limits:
              memory: "128Mi"
              cpu: '0.50'