apiVersion: v1
kind: ServiceAccount
metadata:
  name: phenovar-token-upsert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: phenovar-token-upsert
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["phenovar-token"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phenovar-token-upsert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: phenovar-token-upsert
subjects:
  - kind: ServiceAccount
    name: phenovar-token-upsert